matrix:
  include:
  - language: node_js
    env: LANE='node'
    node_js: 8
    cache: yarn
  - language: android
    env: LANE='android'
    sudo: required
    jdk: oraclejdk8
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - "$HOME/.yarn-cache"
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.2
        - android-27
        - extra-google-google_play_services
    before_install:
      - nvm install 8
    before_script:
      - npm install -g yarn
      - yarn install
      - cp google-services.json.dist android/app/google-services.json
    script:
      - cd android && ./gradlew clean && ./gradlew assembleDebug --stacktrace
  - language: objective-c
    env: LANE='ios'
    os: osx
    osx_image: xcode9.3
    xcode_project: CoopCycle.xcodeproj
    xcode_scheme: CoopCycleTests
    cache:
      - bundler
      - yarn
    before_install:
      - nvm install 8
      - gem install xcpretty
      - npm install -g yarn
      - yarn install
      - cd ios
    script:
      - xcodebuild -workspace CoopCycle.xcworkspace -scheme CoopCycle -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}

notifications:
  email: false

